version: "3"

services:
  pg:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    image: postgres:12.3-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    shm_size: "128m"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ./db/
    entrypoint: ''
    environment:
      DB_SOURCE: postgres://postgres@pg/?sslmode=disable
    depends_on:
      pg:
        condition: service_healthy
